#!/usr/bin/env bash
# configure nginx to listen on port 80 with less lines
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
