#!/usr/bin/env bash
# configure nginx to listen on port 80

# configure nginx to listen on port 80 for all active IPV4 Ips
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
# terminate the first nginx process
kill "$(pgrep 'nginx' | head -1)"
